-- Migration: Dedup, Search Profiles & Auto-Enrich Pipeline
-- Created: 2026-03-30
-- Description: Adds google_place_id for dedup, search_profiles table for automated
--              scraping, and a trigger to auto-enrich new google_maps companies.

-- =============================================================================
-- 1. DEDUP: Add google_place_id to companies
-- =============================================================================

ALTER TABLE companies ADD COLUMN IF NOT EXISTS google_place_id text;

-- Unique constraint prevents importing the same Google Maps place twice
CREATE UNIQUE INDEX IF NOT EXISTS idx_companies_google_place_id
  ON companies(google_place_id)
  WHERE google_place_id IS NOT NULL;

-- =============================================================================
-- 2. SEARCH PROFILES: Automated search configuration
-- =============================================================================

CREATE TABLE IF NOT EXISTS search_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,                          -- "Restauranger Östersund"
  query_template text NOT NULL,                -- "{bransch} i {stad}"
  branch text NOT NULL,                        -- "restauranger", "frisörer"
  city text NOT NULL,                          -- "Östersund", "Stockholm"
  extra_keywords text[] DEFAULT '{}',          -- Additional search refinement
  min_rating numeric(2,1) DEFAULT 0,           -- Minimum Google rating filter
  max_results integer DEFAULT 20,              -- Results per search (1-50)
  is_active boolean DEFAULT true,              -- Enable/disable profile
  auto_enrich boolean DEFAULT true,            -- Auto-enrich imported companies
  last_run_at timestamp with time zone,        -- When this profile last executed
  last_run_results integer DEFAULT 0,          -- How many new leads last run produced
  total_leads_generated integer DEFAULT 0,     -- Lifetime leads from this profile
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),

  CONSTRAINT chk_search_profiles_max_results CHECK (max_results >= 1 AND max_results <= 50),
  CONSTRAINT chk_search_profiles_min_rating CHECK (min_rating >= 0 AND min_rating <= 5)
);

ALTER TABLE search_profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage search profiles"
  ON search_profiles FOR ALL
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

GRANT SELECT, INSERT, UPDATE, DELETE ON search_profiles TO authenticated;

-- =============================================================================
-- 3. SCRAPE LOG: Track automated scrape runs
-- =============================================================================

CREATE TABLE IF NOT EXISTS scrape_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  search_profile_id bigint REFERENCES search_profiles(id) ON DELETE SET NULL,
  query text NOT NULL,                         -- Actual query executed
  source text NOT NULL DEFAULT 'google_maps',
  total_found integer DEFAULT 0,               -- Total results from API
  new_imported integer DEFAULT 0,              -- After dedup filtering
  duplicates_skipped integer DEFAULT 0,        -- Already existed
  auto_enriched integer DEFAULT 0,             -- Successfully enriched
  status text NOT NULL DEFAULT 'pending',
  error_message text,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,

  CONSTRAINT chk_scrape_runs_status CHECK (status IN (
    'pending', 'running', 'completed', 'failed', 'partial'
  ))
);

ALTER TABLE scrape_runs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view scrape runs"
  ON scrape_runs FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can insert scrape runs"
  ON scrape_runs FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update scrape runs"
  ON scrape_runs FOR UPDATE
  USING (auth.role() = 'authenticated');

GRANT SELECT, INSERT, UPDATE ON scrape_runs TO authenticated;

CREATE INDEX IF NOT EXISTS idx_scrape_runs_profile ON scrape_runs(search_profile_id);
CREATE INDEX IF NOT EXISTS idx_scrape_runs_status ON scrape_runs(status);

-- =============================================================================
-- 4. UPDATE ENRICHMENT LOG SOURCE CONSTRAINT
-- =============================================================================
-- Add 'auto_scrape' as valid enrichment source

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'chk_enrichment_log_source'
      AND table_name = 'enrichment_log'
  ) THEN
    ALTER TABLE enrichment_log DROP CONSTRAINT chk_enrichment_log_source;
  END IF;

  ALTER TABLE enrichment_log
    ADD CONSTRAINT chk_enrichment_log_source CHECK (source IN (
      'google_search', 'pagespeed', 'manual', 'allabolag', 'website', 'auto_scrape'
    ));
END $$;

-- =============================================================================
-- 5. UPDATE COMPANIES_SUMMARY VIEW (add google_place_id)
-- =============================================================================

DROP VIEW IF EXISTS companies_summary;

CREATE VIEW companies_summary
WITH (security_invoker=on)
AS
SELECT
  c.id,
  c.created_at,
  c.name,
  c.sector,
  c.size,
  c.linkedin_url,
  c.website,
  c.phone_number,
  c.address,
  c.zipcode,
  c.city,
  c.state_abbr,
  c.sales_id,
  c.context_links,
  c.country,
  c.description,
  c.revenue,
  c.tax_identifier,
  c.logo,
  c.org_number,
  c.google_business_url,
  c.has_website,
  c.website_quality,
  c.source,
  c.lead_status,
  c.next_followup_date,
  c.assigned_to,
  c.tags,
  c.industry,
  c.employees_estimate,
  c.lead_score,
  c.enrichment_data,
  c.enriched_at,
  c.segment,
  c.facebook_url,
  c.instagram_url,
  c.has_facebook,
  c.has_instagram,
  c.website_score,
  c.google_place_id,
  COUNT(DISTINCT d.id) AS nb_deals,
  COUNT(DISTINCT co.id) AS nb_contacts
FROM companies c
LEFT JOIN deals d ON c.id = d.company_id
LEFT JOIN contacts co ON c.id = co.company_id
GROUP BY c.id;

GRANT SELECT ON companies_summary TO authenticated, anon;
