-- Migration: Google Sheet lead import pipeline
-- Created: 2026-04-10
-- Description: Adds import source/run tables, company import metadata,
--              prospecting status, and exposes the fields in companies_summary.

-- =============================================================================
-- 1. IMPORT SOURCE CONFIGURATION
-- =============================================================================

CREATE TABLE IF NOT EXISTS lead_import_sources (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  source_type text NOT NULL DEFAULT 'google_sheet_csv',
  sheet_url text NOT NULL,
  sheet_gid text,
  is_active boolean NOT NULL DEFAULT false,
  batch_size_default integer NOT NULL DEFAULT 50,
  last_imported_row integer NOT NULL DEFAULT 1,
  last_successful_run_at timestamp with time zone,
  last_run_status text NOT NULL DEFAULT 'idle',
  last_run_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),

  CONSTRAINT chk_lead_import_sources_source_type
    CHECK (source_type IN ('google_sheet_csv')),
  CONSTRAINT chk_lead_import_sources_batch_size
    CHECK (batch_size_default > 0),
  CONSTRAINT chk_lead_import_sources_last_imported_row
    CHECK (last_imported_row >= 1),
  CONSTRAINT chk_lead_import_sources_last_run_status
    CHECK (last_run_status IN ('idle', 'running', 'success', 'partial', 'failed'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_lead_import_sources_single_active
  ON lead_import_sources ((is_active))
  WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_lead_import_sources_active
  ON lead_import_sources(is_active);

CREATE OR REPLACE FUNCTION update_lead_import_sources_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '';

CREATE OR REPLACE FUNCTION claim_lead_import_source(
  p_source_id bigint,
  p_stale_before timestamp with time zone
)
RETURNS SETOF lead_import_sources
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
BEGIN
  RETURN QUERY
  UPDATE public.lead_import_sources
  SET
    last_run_status = 'running',
    last_run_message = null,
    updated_at = now()
  WHERE id = p_source_id
    AND (
      last_run_status <> 'running'
      OR updated_at < p_stale_before
    )
  RETURNING *;
END;
$$;

DROP TRIGGER IF EXISTS lead_import_sources_updated_at_trigger ON lead_import_sources;
CREATE TRIGGER lead_import_sources_updated_at_trigger
  BEFORE UPDATE ON lead_import_sources
  FOR EACH ROW
  EXECUTE FUNCTION update_lead_import_sources_updated_at();

ALTER TABLE lead_import_sources ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view lead import sources" ON lead_import_sources
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Users can insert lead import sources" ON lead_import_sources
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can update lead import sources" ON lead_import_sources
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Users can delete lead import sources" ON lead_import_sources
  FOR DELETE USING (
    EXISTS (
      SELECT 1
      FROM public.sales
      WHERE user_id = auth.uid()
        AND administrator = true
    )
  );

-- =============================================================================
-- 2. IMPORT RUN LOGS
-- =============================================================================

CREATE TABLE IF NOT EXISTS lead_import_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id bigint NOT NULL REFERENCES lead_import_sources(id) ON DELETE CASCADE,
  triggered_by text NOT NULL,
  requested_batch_size integer NOT NULL,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  finished_at timestamp with time zone,
  rows_scanned integer NOT NULL DEFAULT 0,
  rows_inserted integer NOT NULL DEFAULT 0,
  rows_skipped_duplicates integer NOT NULL DEFAULT 0,
  rows_failed integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'running',
  error_summary text,
  imported_company_ids jsonb NOT NULL DEFAULT '[]'::jsonb,

  CONSTRAINT chk_lead_import_runs_triggered_by
    CHECK (triggered_by IN ('manual', 'scheduled')),
  CONSTRAINT chk_lead_import_runs_requested_batch_size
    CHECK (requested_batch_size > 0),
  CONSTRAINT chk_lead_import_runs_status
    CHECK (status IN ('running', 'success', 'partial', 'failed'))
);

CREATE INDEX IF NOT EXISTS idx_lead_import_runs_source_id
  ON lead_import_runs(source_id);

CREATE INDEX IF NOT EXISTS idx_lead_import_runs_started_at
  ON lead_import_runs(started_at DESC);

CREATE INDEX IF NOT EXISTS idx_lead_import_runs_status
  ON lead_import_runs(status);

ALTER TABLE lead_import_runs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view lead import runs" ON lead_import_runs
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Users can insert lead import runs" ON lead_import_runs
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can update lead import runs" ON lead_import_runs
  FOR UPDATE USING (auth.role() = 'authenticated');

-- =============================================================================
-- 3. COMPANY IMPORT METADATA
-- =============================================================================

ALTER TABLE companies
  ADD COLUMN IF NOT EXISTS import_source_id bigint REFERENCES lead_import_sources(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS import_run_id bigint REFERENCES lead_import_runs(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS source_row_number integer,
  ADD COLUMN IF NOT EXISTS processing_order integer,
  ADD COLUMN IF NOT EXISTS prospecting_status text;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'chk_companies_prospecting_status'
      AND table_name = 'companies'
  ) THEN
    ALTER TABLE companies DROP CONSTRAINT chk_companies_prospecting_status;
  END IF;

  ALTER TABLE companies
    ADD CONSTRAINT chk_companies_prospecting_status
    CHECK (
      prospecting_status IS NULL OR prospecting_status IN (
        'imported',
        'enriching',
        'call_ready',
        'needs_review',
        'completed',
        'disqualified'
      )
    );
END $$;

CREATE INDEX IF NOT EXISTS idx_companies_import_source_id
  ON companies(import_source_id);

CREATE INDEX IF NOT EXISTS idx_companies_import_run_id
  ON companies(import_run_id);

CREATE INDEX IF NOT EXISTS idx_companies_processing_order
  ON companies(processing_order);

CREATE INDEX IF NOT EXISTS idx_companies_prospecting_status
  ON companies(prospecting_status);

CREATE INDEX IF NOT EXISTS idx_companies_call_ready_processing_order
  ON companies(processing_order)
  WHERE prospecting_status = 'call_ready';

-- =============================================================================
-- 4. COMPANIES SUMMARY VIEW
-- =============================================================================

DROP VIEW IF EXISTS companies_summary;

CREATE VIEW companies_summary
WITH (security_invoker=on)
AS
SELECT
  c.id,
  c.created_at,
  c.name,
  c.sector,
  c.size,
  c.linkedin_url,
  c.website,
  c.phone_number,
  c.email,
  c.address,
  c.zipcode,
  c.city,
  c.state_abbr,
  c.sales_id,
  c.context_links,
  c.country,
  c.description,
  c.revenue,
  c.tax_identifier,
  c.logo,
  c.org_number,
  c.google_business_url,
  c.has_website,
  c.website_quality,
  c.source,
  c.lead_status,
  c.next_followup_date,
  c.assigned_to,
  c.tags,
  c.industry,
  c.employees_estimate,
  c.lead_score,
  c.enrichment_data,
  c.enriched_at,
  c.segment,
  c.facebook_url,
  c.instagram_url,
  c.has_facebook,
  c.has_instagram,
  c.website_score,
  c.pipeline_state,
  c.owner_sales_id,
  c.last_touch_at,
  c.last_touch_type,
  c.next_action_at,
  c.next_action_type,
  c.next_action_note,
  c.priority_score,
  c.data_quality_status,
  c.import_source_id,
  c.import_run_id,
  c.source_row_number,
  c.processing_order,
  c.prospecting_status,
  COUNT(DISTINCT d.id) AS nb_deals,
  COUNT(DISTINCT co.id) AS nb_contacts
FROM companies c
LEFT JOIN deals d ON c.id = d.company_id
LEFT JOIN contacts co ON c.id = co.company_id
GROUP BY c.id;

GRANT SELECT ON companies_summary TO authenticated, anon;

-- =============================================================================
-- 5. ACCESS
-- =============================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON lead_import_sources TO authenticated;
GRANT SELECT, INSERT, UPDATE ON lead_import_runs TO authenticated;
GRANT USAGE ON SEQUENCE lead_import_sources_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE lead_import_runs_id_seq TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON lead_import_sources TO service_role;
GRANT SELECT, INSERT, UPDATE ON lead_import_runs TO service_role;
GRANT USAGE ON SEQUENCE lead_import_sources_id_seq TO service_role;
GRANT USAGE ON SEQUENCE lead_import_runs_id_seq TO service_role;
GRANT EXECUTE ON FUNCTION claim_lead_import_source(bigint, timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION claim_lead_import_source(bigint, timestamp with time zone) TO service_role;

INSERT INTO lead_import_sources (
  name,
  source_type,
  sheet_url,
  sheet_gid,
  is_active,
  batch_size_default,
  last_imported_row,
  last_run_status
)
SELECT
  'Jämtland/Härjedalen leads',
  'google_sheet_csv',
  'https://docs.google.com/spreadsheets/d/1n2PpKwDkIpQ7jx_xRrf4v776pyYnGgfA1U8h9zQYC6o/edit?gid=2056365843#gid=2056365843',
  '2056365843',
  true,
  50,
  1,
  'idle'
WHERE NOT EXISTS (
  SELECT 1 FROM lead_import_sources
);
