-- Migration: Create scanner_public_requests table
-- Created: 2026-07-28
-- Description: Requestlogg för scannerns publika självscan (Fas 2,
--              scanner.axonadigital.se). En rad per publikt scan-försök —
--              underlag för rate limiting (per IP-hash och globalt per dygn)
--              och spårbarhet lead ↔ scan. IP lagras ALDRIG i klartext,
--              bara som saltad SHA-256-hash (GDPR). Skrivs/läses enbart via
--              scannerns service role. Helt additiv migration — inga
--              DROP/ALTER på befintliga objekt.

CREATE TABLE IF NOT EXISTS "public"."scanner_public_requests" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Saltad SHA-256 av besökarens IP (saltet ligger i scannerns env)
  "ip_hash" text NOT NULL,
  -- Kanonisk form av den scannade URL:en (värdnamn utan www + path)
  "url_normalized" text NOT NULL,
  -- Besökarens e-post (e-postgrind före scan); null om grinden är avstängd
  "email" text,
  -- Scannen som requesten resulterade i (null vid avvisad/misslyckad request)
  "scan_id" bigint REFERENCES scanner_scans(id) ON DELETE SET NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."scanner_public_requests" ENABLE ROW LEVEL SECURITY;

-- Ingen policy alls: varken anon eller authenticated behöver läsa loggen.
-- Scannerns service role förbigår RLS för både läsning (räknare) och skrivning.

CREATE INDEX IF NOT EXISTS idx_scanner_public_requests_ip_created
  ON scanner_public_requests(ip_hash, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_scanner_public_requests_url_created
  ON scanner_public_requests(url_normalized, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_scanner_public_requests_created
  ON scanner_public_requests(created_at DESC);
