-- Migration: Enrichment & Lead Scoring
-- Created: 2026-03-28
-- Description: Adds enrichment fields (social media, website score, lead score, segment)
--              to companies table, creates enrichment_log table, and updates companies_summary view.

-- =============================================================================
-- 1. ADD ENRICHMENT COLUMNS TO COMPANIES
-- =============================================================================

ALTER TABLE companies ADD COLUMN IF NOT EXISTS lead_score integer DEFAULT 0;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS enrichment_data jsonb;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS enriched_at timestamp with time zone;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS segment text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS facebook_url text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS instagram_url text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS has_facebook boolean DEFAULT false;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS has_instagram boolean DEFAULT false;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS website_score integer;

-- =============================================================================
-- 2. ADD CHECK CONSTRAINTS
-- =============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'chk_companies_segment'
      AND table_name = 'companies'
  ) THEN
    ALTER TABLE companies
      ADD CONSTRAINT chk_companies_segment
      CHECK (segment IS NULL OR segment IN (
        'hot_lead', 'warm_lead', 'cold_lead', 'nurture', 'disqualified'
      ));
  END IF;
END $$;

-- Update existing source constraint to allow additional sources
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'chk_companies_source'
      AND table_name = 'companies'
  ) THEN
    ALTER TABLE companies DROP CONSTRAINT chk_companies_source;
  END IF;

  ALTER TABLE companies
    ADD CONSTRAINT chk_companies_source
    CHECK (source IS NULL OR source IN (
      'manual', 'google_maps', 'google_search', 'import', 'website', 'referral',
      'hitta', 'allabolag', 'eniro', 'field'
    ));
END $$;

-- Update existing lead_status constraint to include all 10 statuses
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'chk_companies_lead_status'
      AND table_name = 'companies'
  ) THEN
    ALTER TABLE companies DROP CONSTRAINT chk_companies_lead_status;
  END IF;

  ALTER TABLE companies
    ADD CONSTRAINT chk_companies_lead_status
    CHECK (lead_status IS NULL OR lead_status IN (
      'new', 'contacted', 'interested', 'meeting_booked', 'proposal_sent',
      'negotiation', 'closed_won', 'closed_lost', 'not_interested', 'bad_fit'
    ));
END $$;

-- Update website_quality constraint to include 'good'
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'chk_companies_website_quality'
      AND table_name = 'companies'
  ) THEN
    ALTER TABLE companies DROP CONSTRAINT chk_companies_website_quality;
  END IF;

  ALTER TABLE companies
    ADD CONSTRAINT chk_companies_website_quality
    CHECK (website_quality IS NULL OR website_quality IN (
      'none', 'poor', 'ok', 'good'
    ));
END $$;

-- =============================================================================
-- 3. ADD INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_companies_lead_score ON companies(lead_score DESC);
CREATE INDEX IF NOT EXISTS idx_companies_segment ON companies(segment);
CREATE INDEX IF NOT EXISTS idx_companies_has_facebook ON companies(has_facebook) WHERE has_facebook = true;
CREATE INDEX IF NOT EXISTS idx_companies_has_instagram ON companies(has_instagram) WHERE has_instagram = true;

-- =============================================================================
-- 4. CREATE ENRICHMENT_LOG TABLE
-- =============================================================================

CREATE TABLE IF NOT EXISTS enrichment_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  source text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  enrichment_data jsonb,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),

  CONSTRAINT chk_enrichment_log_source CHECK (source IN (
    'google_search', 'pagespeed', 'manual', 'allabolag', 'website'
  )),
  CONSTRAINT chk_enrichment_log_status CHECK (status IN (
    'pending', 'success', 'failed', 'partial'
  ))
);

CREATE INDEX IF NOT EXISTS idx_enrichment_log_company_id ON enrichment_log(company_id);

ALTER TABLE enrichment_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view enrichment logs" ON enrichment_log
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Users can insert enrichment logs" ON enrichment_log
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- =============================================================================
-- 5. UPDATE COMPANIES_SUMMARY VIEW
-- =============================================================================

DROP VIEW IF EXISTS companies_summary;

CREATE VIEW companies_summary
WITH (security_invoker=on)
AS
SELECT
  c.id,
  c.created_at,
  c.name,
  c.sector,
  c.size,
  c.linkedin_url,
  c.website,
  c.phone_number,
  c.address,
  c.zipcode,
  c.city,
  c.state_abbr,
  c.sales_id,
  c.context_links,
  c.country,
  c.description,
  c.revenue,
  c.tax_identifier,
  c.logo,
  c.org_number,
  c.google_business_url,
  c.has_website,
  c.website_quality,
  c.source,
  c.lead_status,
  c.next_followup_date,
  c.assigned_to,
  c.tags,
  c.industry,
  c.employees_estimate,
  c.lead_score,
  c.enrichment_data,
  c.enriched_at,
  c.segment,
  c.facebook_url,
  c.instagram_url,
  c.has_facebook,
  c.has_instagram,
  c.website_score,
  COUNT(DISTINCT d.id) AS nb_deals,
  COUNT(DISTINCT co.id) AS nb_contacts
FROM companies c
LEFT JOIN deals d ON c.id = d.company_id
LEFT JOIN contacts co ON c.id = co.company_id
GROUP BY c.id;

GRANT SELECT ON companies_summary TO authenticated, anon;
