-- Migration: Create quotes and quote_line_items tables
-- Created: 2026-03-26
-- Description: Stores quotes/proposals linked to companies and contacts, with line items for services

CREATE TABLE IF NOT EXISTS "public"."quotes" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "company_id" bigint NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  "contact_id" bigint REFERENCES contacts(id) ON DELETE SET NULL,
  "deal_id" bigint REFERENCES deals(id) ON DELETE SET NULL,
  "sales_id" bigint REFERENCES sales(id) ON DELETE SET NULL,
  "status" text NOT NULL DEFAULT 'draft' CHECK (status IN (
    'draft', 'generated', 'sent', 'viewed', 'signed', 'declined', 'expired'
  )),
  "generated_text" text,
  "custom_text" text,
  "total_amount" numeric(12,2) DEFAULT 0,
  "currency" text DEFAULT 'SEK',
  "valid_until" date,
  "docuseal_submission_id" text,
  "docuseal_document_url" text,
  "pdf_url" text,
  "signed_at" timestamp with time zone,
  "sent_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Enable RLS
ALTER TABLE "public"."quotes" ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view quotes" ON "public"."quotes"
  FOR SELECT
  USING (true);

CREATE POLICY "Users can insert quotes" ON "public"."quotes"
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Users can update quotes" ON "public"."quotes"
  FOR UPDATE
  USING (true);

CREATE POLICY "Users can delete draft quotes" ON "public"."quotes"
  FOR DELETE
  USING (status = 'draft');

-- Indexes
CREATE INDEX idx_quotes_company_id ON quotes(company_id);
CREATE INDEX idx_quotes_contact_id ON quotes(contact_id);
CREATE INDEX idx_quotes_deal_id ON quotes(deal_id);
CREATE INDEX idx_quotes_sales_id ON quotes(sales_id);
CREATE INDEX idx_quotes_status ON quotes(status);
CREATE INDEX idx_quotes_created_at ON quotes(created_at DESC);

-- Line items table
CREATE TABLE IF NOT EXISTS "public"."quote_line_items" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "quote_id" bigint NOT NULL REFERENCES quotes(id) ON DELETE CASCADE,
  "description" text NOT NULL,
  "quantity" numeric(10,2) DEFAULT 1,
  "unit_price" numeric(12,2) NOT NULL,
  "total" numeric(12,2) GENERATED ALWAYS AS (quantity * unit_price) STORED,
  "sort_order" smallint DEFAULT 0,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Enable RLS
ALTER TABLE "public"."quote_line_items" ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view quote_line_items" ON "public"."quote_line_items"
  FOR SELECT
  USING (true);

CREATE POLICY "Users can insert quote_line_items" ON "public"."quote_line_items"
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Users can update quote_line_items" ON "public"."quote_line_items"
  FOR UPDATE
  USING (true);

CREATE POLICY "Users can delete quote_line_items" ON "public"."quote_line_items"
  FOR DELETE
  USING (true);

-- Indexes
CREATE INDEX idx_quote_line_items_quote_id ON quote_line_items(quote_id);

-- Trigger to auto-update total_amount on quotes when line items change
CREATE OR REPLACE FUNCTION update_quote_total()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE quotes
  SET total_amount = (
    SELECT COALESCE(SUM(quantity * unit_price), 0)
    FROM quote_line_items
    WHERE quote_id = COALESCE(NEW.quote_id, OLD.quote_id)
  ),
  updated_at = now()
  WHERE id = COALESCE(NEW.quote_id, OLD.quote_id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER quote_line_items_total_trigger
AFTER INSERT OR UPDATE OR DELETE ON quote_line_items
FOR EACH ROW EXECUTE FUNCTION update_quote_total();

-- Trigger to auto-update updated_at on quotes
CREATE OR REPLACE FUNCTION update_quotes_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER quotes_updated_at_trigger
BEFORE UPDATE ON quotes
FOR EACH ROW EXECUTE FUNCTION update_quotes_updated_at();
