-- Migration: Meeting Transcriptions & Analysis
-- Created: 2026-03-28
-- Description: Creates meeting_transcriptions table for storing transcription text
--              and AI-generated analysis (summary, needs, objections, action items).

CREATE TABLE IF NOT EXISTS meeting_transcriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  calendar_event_id bigint REFERENCES calendar_events(id) ON DELETE CASCADE,
  contact_id bigint REFERENCES contacts(id) ON DELETE SET NULL,
  company_id bigint REFERENCES companies(id) ON DELETE SET NULL,
  transcription_text text NOT NULL,
  transcription_source text NOT NULL DEFAULT 'manual',
  analysis jsonb,
  analyzed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),

  CONSTRAINT chk_transcription_source CHECK (transcription_source IN (
    'manual', 'fireflies', 'whisper', 'google_meet'
  ))
);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_meeting_transcriptions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '';

CREATE TRIGGER meeting_transcriptions_updated_at_trigger
  BEFORE UPDATE ON meeting_transcriptions
  FOR EACH ROW
  EXECUTE FUNCTION update_meeting_transcriptions_updated_at();

-- RLS
ALTER TABLE meeting_transcriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view meeting transcriptions" ON meeting_transcriptions
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Users can insert meeting transcriptions" ON meeting_transcriptions
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can update meeting transcriptions" ON meeting_transcriptions
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Users can delete meeting transcriptions" ON meeting_transcriptions
  FOR DELETE USING (auth.role() = 'authenticated');

-- Indexes
CREATE INDEX IF NOT EXISTS idx_meeting_transcriptions_event ON meeting_transcriptions(calendar_event_id);
CREATE INDEX IF NOT EXISTS idx_meeting_transcriptions_contact ON meeting_transcriptions(contact_id);
CREATE INDEX IF NOT EXISTS idx_meeting_transcriptions_company ON meeting_transcriptions(company_id);

-- Grant access
GRANT SELECT, INSERT, UPDATE, DELETE ON meeting_transcriptions TO authenticated;
GRANT USAGE ON SEQUENCE meeting_transcriptions_id_seq TO authenticated;
