-- Migration: Email Sequences
-- Created: 2026-03-28
-- Description: Creates tables for automated email sequences: sequence definitions,
--              steps within sequences, and enrollment tracking for contacts.

-- =============================================================================
-- 1. SEQUENCES TABLE
-- =============================================================================

CREATE TABLE IF NOT EXISTS sequences (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'draft',
  trigger_type text NOT NULL DEFAULT 'manual',
  trigger_config jsonb DEFAULT '{}',
  created_by bigint REFERENCES sales(id) ON DELETE SET NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),

  CONSTRAINT chk_sequences_status CHECK (status IN ('draft', 'active', 'paused')),
  CONSTRAINT chk_sequences_trigger_type CHECK (trigger_type IN (
    'manual', 'new_lead', 'segment_change'
  ))
);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_sequences_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '';

CREATE TRIGGER sequences_updated_at_trigger
  BEFORE UPDATE ON sequences
  FOR EACH ROW
  EXECUTE FUNCTION update_sequences_updated_at();

-- RLS
ALTER TABLE sequences ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view sequences" ON sequences
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Users can insert sequences" ON sequences
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can update sequences" ON sequences
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Users can delete sequences" ON sequences
  FOR DELETE USING (auth.role() = 'authenticated');

-- Indexes
CREATE INDEX IF NOT EXISTS idx_sequences_status ON sequences(status);
CREATE INDEX IF NOT EXISTS idx_sequences_trigger_type ON sequences(trigger_type);

-- =============================================================================
-- 2. SEQUENCE STEPS TABLE
-- =============================================================================

CREATE TABLE IF NOT EXISTS sequence_steps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sequence_id bigint NOT NULL REFERENCES sequences(id) ON DELETE CASCADE,
  step_number integer NOT NULL DEFAULT 1,
  delay_days integer NOT NULL DEFAULT 0,
  delay_hours integer NOT NULL DEFAULT 0,
  action_type text NOT NULL DEFAULT 'send_email',
  template_id bigint REFERENCES email_templates(id) ON DELETE SET NULL,
  action_config jsonb DEFAULT '{}',
  created_at timestamp with time zone DEFAULT now(),

  CONSTRAINT chk_sequence_steps_action_type CHECK (action_type IN (
    'send_email', 'create_task', 'update_lead_status'
  )),
  CONSTRAINT chk_sequence_steps_delay CHECK (delay_days >= 0 AND delay_hours >= 0),
  UNIQUE(sequence_id, step_number)
);

-- RLS
ALTER TABLE sequence_steps ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view sequence steps" ON sequence_steps
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Users can insert sequence steps" ON sequence_steps
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can update sequence steps" ON sequence_steps
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Users can delete sequence steps" ON sequence_steps
  FOR DELETE USING (auth.role() = 'authenticated');

-- Indexes
CREATE INDEX IF NOT EXISTS idx_sequence_steps_sequence_id ON sequence_steps(sequence_id);
CREATE INDEX IF NOT EXISTS idx_sequence_steps_template_id ON sequence_steps(template_id);

-- =============================================================================
-- 3. SEQUENCE ENROLLMENTS TABLE
-- =============================================================================

CREATE TABLE IF NOT EXISTS sequence_enrollments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sequence_id bigint NOT NULL REFERENCES sequences(id) ON DELETE CASCADE,
  contact_id bigint NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  company_id bigint REFERENCES companies(id) ON DELETE SET NULL,
  current_step integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'active',
  next_action_at timestamp with time zone,
  enrolled_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  paused_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),

  CONSTRAINT chk_sequence_enrollments_status CHECK (status IN (
    'active', 'completed', 'paused', 'bounced', 'replied', 'unsubscribed'
  )),
  -- Prevent enrolling same contact in same sequence twice
  UNIQUE(sequence_id, contact_id)
);

-- RLS
ALTER TABLE sequence_enrollments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view sequence enrollments" ON sequence_enrollments
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Users can insert sequence enrollments" ON sequence_enrollments
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can update sequence enrollments" ON sequence_enrollments
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Users can delete sequence enrollments" ON sequence_enrollments
  FOR DELETE USING (auth.role() = 'authenticated');

-- Indexes: critical for the processor query
CREATE INDEX IF NOT EXISTS idx_sequence_enrollments_sequence_id ON sequence_enrollments(sequence_id);
CREATE INDEX IF NOT EXISTS idx_sequence_enrollments_contact_id ON sequence_enrollments(contact_id);
CREATE INDEX IF NOT EXISTS idx_sequence_enrollments_status ON sequence_enrollments(status);
CREATE INDEX IF NOT EXISTS idx_sequence_enrollments_next_action
  ON sequence_enrollments(next_action_at)
  WHERE status = 'active' AND next_action_at IS NOT NULL;

-- =============================================================================
-- 4. GRANT ACCESS
-- =============================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON sequences TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON sequence_steps TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON sequence_enrollments TO authenticated;
GRANT USAGE ON SEQUENCE sequences_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE sequence_steps_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE sequence_enrollments_id_seq TO authenticated;
