-- Migration: Email Templates & Sends
-- Created: 2026-03-28
-- Description: Creates email_templates table for reusable email templates with variable placeholders,
--              and email_sends table for tracking outbound email delivery status via Postmark.

-- =============================================================================
-- 1. EMAIL TEMPLATES TABLE
-- =============================================================================

CREATE TABLE IF NOT EXISTS email_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  subject text NOT NULL,
  body text NOT NULL,
  category text NOT NULL DEFAULT 'outreach',
  language text DEFAULT 'sv',
  created_by bigint REFERENCES sales(id) ON DELETE SET NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),

  CONSTRAINT chk_email_templates_category CHECK (category IN (
    'outreach', 'followup', 'meeting_request', 'proposal', 'thank_you'
  ))
);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_email_templates_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '';

CREATE TRIGGER email_templates_updated_at_trigger
  BEFORE UPDATE ON email_templates
  FOR EACH ROW
  EXECUTE FUNCTION update_email_templates_updated_at();

-- RLS
ALTER TABLE email_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view email templates" ON email_templates
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Users can insert email templates" ON email_templates
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can update email templates" ON email_templates
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Users can delete email templates" ON email_templates
  FOR DELETE USING (auth.role() = 'authenticated');

-- Indexes
CREATE INDEX IF NOT EXISTS idx_email_templates_category ON email_templates(category);
CREATE INDEX IF NOT EXISTS idx_email_templates_created_by ON email_templates(created_by);

-- =============================================================================
-- 2. EMAIL SENDS TABLE
-- =============================================================================

CREATE TABLE IF NOT EXISTS email_sends (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id bigint REFERENCES email_templates(id) ON DELETE SET NULL,
  contact_id bigint REFERENCES contacts(id) ON DELETE SET NULL,
  company_id bigint REFERENCES companies(id) ON DELETE SET NULL,
  sales_id bigint REFERENCES sales(id) ON DELETE SET NULL,
  subject text NOT NULL,
  body text NOT NULL,
  to_email text NOT NULL,
  from_email text,
  status text NOT NULL DEFAULT 'queued',
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  opened_at timestamp with time zone,
  clicked_at timestamp with time zone,
  bounced_at timestamp with time zone,
  postmark_message_id text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),

  CONSTRAINT chk_email_sends_status CHECK (status IN (
    'queued', 'sent', 'delivered', 'opened', 'clicked', 'bounced', 'complained'
  ))
);

-- RLS
ALTER TABLE email_sends ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view email sends" ON email_sends
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Users can insert email sends" ON email_sends
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can update email sends" ON email_sends
  FOR UPDATE USING (auth.role() = 'authenticated');

-- Indexes
CREATE INDEX IF NOT EXISTS idx_email_sends_template_id ON email_sends(template_id);
CREATE INDEX IF NOT EXISTS idx_email_sends_contact_id ON email_sends(contact_id);
CREATE INDEX IF NOT EXISTS idx_email_sends_company_id ON email_sends(company_id);
CREATE INDEX IF NOT EXISTS idx_email_sends_sales_id ON email_sends(sales_id);
CREATE INDEX IF NOT EXISTS idx_email_sends_status ON email_sends(status);
CREATE INDEX IF NOT EXISTS idx_email_sends_created_at ON email_sends(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_email_sends_postmark_id ON email_sends(postmark_message_id) WHERE postmark_message_id IS NOT NULL;

-- =============================================================================
-- 3. GRANT ACCESS
-- =============================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON email_templates TO authenticated;
GRANT SELECT, INSERT, UPDATE ON email_sends TO authenticated;
GRANT USAGE ON SEQUENCE email_templates_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE email_sends_id_seq TO authenticated;
