-- Migration: report_pipeline_queue + kö-baserad månadscron
-- Created: 2026-07-07
-- Description: Ersätter de två "gör allt i en enda edge-anrop"-cronjobben
--              (monthly-website-snapshots, monthly-reports) med en kö-tabell +
--              återkommande "tick". Bakgrund: ett enda cron-anrop som skulle
--              analysera alla kunder i en körning hann inte klart innan
--              Supabase-funktionens tidsgräns slog till — en del kunder
--              bearbetades aldrig, helt tyst. Kö-mönstret skalar till
--              godtyckligt antal kunder utan kodändring: ett litet antal
--              rader plockas upp var 5:e minut tills kön är tom.
--              Helt additiv migration — inga DROP/ALTER på befintliga objekt
--              förutom att de två gamla cron-jobben schemaläggs om (samma
--              mekanism, cron.unschedule/cron.schedule, ingen datadestruktion).

CREATE TABLE IF NOT EXISTS "public"."report_pipeline_queue" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" bigint NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  "period_start" date NOT NULL,
  "period_end" date NOT NULL,
  -- snapshot: analysera hemsidan (analyze_website). report: generera kundrapport
  -- (generate_monthly_reports) — skapas automatiskt när snapshot-steget lyckas.
  "stage" text NOT NULL CHECK (stage IN ('snapshot', 'report')),
  -- pending: väntar på att plockas upp. processing: ett tick håller på just nu
  -- (självläker till pending igen om det tar >15 min, se claim_pipeline_queue_batch).
  -- done / failed: slutligt resultat för perioden.
  "status" text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'processing', 'done', 'failed')),
  "attempts" integer NOT NULL DEFAULT 0,
  "error" text,
  "claimed_at" timestamp with time zone,
  "completed_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."report_pipeline_queue" ENABLE ROW LEVEL SECURITY;

-- Samma öppna mönster som monthly_reports — hela teamet ska kunna se/åtgärda
-- misslyckade rader i CRM:t. Edge-funktionerna skriver via service role.
-- DROP+CREATE (inte bara IF NOT EXISTS) så migrationen är säker att köra om.
DROP POLICY IF EXISTS "Authenticated can view pipeline queue" ON "public"."report_pipeline_queue";
CREATE POLICY "Authenticated can view pipeline queue" ON "public"."report_pipeline_queue"
  FOR SELECT
  USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated can update pipeline queue" ON "public"."report_pipeline_queue";
CREATE POLICY "Authenticated can update pipeline queue" ON "public"."report_pipeline_queue"
  FOR UPDATE
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Identitetskolumnerna (vilken kund/period/steg raden gäller) får aldrig
-- ändras via UPDATE — bara status/error/attempts/tidsstämplar. Skyddar mot en
-- CRM-knapp (t.ex. "Kör om") som av misstag skulle skriva fel company_id.
CREATE OR REPLACE FUNCTION public.prevent_pipeline_queue_identity_change()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $$
BEGIN
  IF NEW.company_id <> OLD.company_id
     OR NEW.period_start <> OLD.period_start
     OR NEW.stage <> OLD.stage THEN
    RAISE EXCEPTION 'report_pipeline_queue: company_id/period_start/stage kan inte ändras efter att raden skapats';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_pipeline_queue_identity_lock ON public.report_pipeline_queue;
CREATE TRIGGER trg_pipeline_queue_identity_lock
  BEFORE UPDATE ON public.report_pipeline_queue
  FOR EACH ROW
  EXECUTE FUNCTION public.prevent_pipeline_queue_identity_change();

-- En rad per kund, period och steg (idempotent seed + idempotent steg-övergång).
CREATE UNIQUE INDEX IF NOT EXISTS idx_pipeline_queue_company_period_stage
  ON report_pipeline_queue(company_id, period_start, stage);
CREATE INDEX IF NOT EXISTS idx_pipeline_queue_claim ON report_pipeline_queue(stage, status);
CREATE INDEX IF NOT EXISTS idx_pipeline_queue_stuck ON report_pipeline_queue(status, created_at);

-- ============================================================================
-- Kö-funktioner
-- ============================================================================

-- Plockar upp max p_batch_size väntande rader för ett steg (analys eller
-- rapport) och markerar dem 'processing'. FOR UPDATE SKIP LOCKED gör att flera
-- samtidiga tick aldrig kan ta samma rad. Rader som fastnat i 'processing' i
-- mer än 15 minuter (kraschad funktion mitt i) återställs till 'pending' här,
-- så inget kan fastna permanent utan att ett fel faktiskt skrivs.
CREATE OR REPLACE FUNCTION public.claim_pipeline_queue_batch(
  p_stage text,
  p_batch_size integer DEFAULT 3
)
RETURNS SETOF public.report_pipeline_queue
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
BEGIN
  UPDATE public.report_pipeline_queue
  SET status = 'pending'
  WHERE stage = p_stage
    AND status = 'processing'
    AND claimed_at < now() - interval '15 minutes';

  RETURN QUERY
  UPDATE public.report_pipeline_queue q
  SET status = 'processing',
      claimed_at = now(),
      attempts = q.attempts + 1
  WHERE q.id IN (
    SELECT id FROM public.report_pipeline_queue
    WHERE stage = p_stage AND status = 'pending'
    ORDER BY id
    FOR UPDATE SKIP LOCKED
    LIMIT p_batch_size
  )
  RETURNING q.*;
END;
$$;

-- Markerar en kö-rad klar. Vid lyckad analys skapas automatiskt nästa steg
-- (report) för samma kund+period — det är så snapshot → rapport hänger ihop
-- utan någon fast tidsgräns mellan dem.
--
-- p_claimed_at måste matcha exakt vad claim_pipeline_queue_batch stämplade när
-- raden plockades upp. Det är en "fencing token": om ett tick tar >15 min och
-- hinner bli självläkt/omclaimad av ett NYTT tick under tiden, får det gamla
-- tickets sena complete-anrop ett claimed_at som inte längre matchar (raden har
-- fått ett nytt claimed_at av omclaimningen) — då är detta ett no-op istället
-- för att skriva över det nya, korrekta resultatet.
CREATE OR REPLACE FUNCTION public.complete_pipeline_queue_item(
  p_id bigint,
  p_success boolean,
  p_error text DEFAULT NULL,
  p_claimed_at timestamp with time zone DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  item public.report_pipeline_queue;
BEGIN
  UPDATE public.report_pipeline_queue
  SET status = CASE WHEN p_success THEN 'done' ELSE 'failed' END,
      error = p_error,
      completed_at = now()
  WHERE id = p_id
    AND status = 'processing'
    AND (p_claimed_at IS NULL OR claimed_at = p_claimed_at)
  RETURNING * INTO item;

  IF item.id IS NULL THEN
    -- Antingen redan slutförd av ett annat (nyare) tick, eller en sen
    -- completion från ett tick som blivit omclaimat under tiden. Ignorera.
    RETURN;
  END IF;

  IF p_success AND item.stage = 'snapshot' THEN
    INSERT INTO public.report_pipeline_queue
      (company_id, period_start, period_end, stage, status)
    VALUES
      (item.company_id, item.period_start, item.period_end, 'report', 'pending')
    ON CONFLICT (company_id, period_start, stage) DO NOTHING;
  END IF;
END;
$$;

-- Fyller kön en gång i månaden: en snapshot-rad per kund med levererad
-- hemsida, för föregående hela kalendermånad. Perioden räknas ut EN gång här
-- och sparas på raden — varje tick räknar INTE om "föregående månad" själv,
-- så alla kunder får exakt samma period oavsett hur länge kön tar att tömma.
CREATE OR REPLACE FUNCTION public.seed_monthly_pipeline_queue()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_period_start date := (date_trunc('month', now() - interval '1 month'))::date;
  v_period_end date := (date_trunc('month', now()) - interval '1 day')::date;
BEGIN
  INSERT INTO public.report_pipeline_queue
    (company_id, period_start, period_end, stage, status)
  SELECT cd.company_id, v_period_start, v_period_end, 'snapshot', 'pending'
  FROM public.customer_details cd
  WHERE cd.delivered_website_url IS NOT NULL
  ON CONFLICT (company_id, period_start, stage) DO NOTHING;
END;
$$;

-- Triggar ett tick (ett litet antal kö-rader) för ett givet steg. Samma
-- vault-mönster som tidigare run_monthly_reports/run_monthly_website_snapshots.
CREATE OR REPLACE FUNCTION public.run_pipeline_tick(p_stage text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  edge_function_url text;
  cron_secret text;
  target_path text;
BEGIN
  SELECT decrypted_secret INTO edge_function_url
  FROM vault.decrypted_secrets WHERE name = 'supabase_url' LIMIT 1;
  SELECT decrypted_secret INTO cron_secret
  FROM vault.decrypted_secrets WHERE name = 'cron_secret' LIMIT 1;

  IF edge_function_url IS NULL OR cron_secret IS NULL THEN
    RAISE WARNING 'run_pipeline_tick(%): missing supabase_url or cron_secret in vault — skipping run', p_stage;
    RETURN;
  END IF;

  target_path := CASE p_stage
    WHEN 'snapshot' THEN '/functions/v1/analyze_website'
    WHEN 'report' THEN '/functions/v1/generate_monthly_reports'
    ELSE NULL
  END;

  IF target_path IS NULL THEN
    RAISE WARNING 'run_pipeline_tick: okänt steg %', p_stage;
    RETURN;
  END IF;

  PERFORM net.http_post(
    url     := edge_function_url || target_path,
    body    := jsonb_build_object('tick', true, 'batch_size', 3),
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-cron-secret', cron_secret
    ),
    timeout_milliseconds := 20000
  );
END;
$$;

-- Daglig hälsokoll: om något legat kvar som pending/failed i mer än ett dygn,
-- skicka en Discord-varning med lista (namn, steg, exakt felmeddelande) så
-- inget tystnar bort. Kräver ingen egen edge-funktion — pratar direkt med
-- Discord-webhooken i vault, samma secret som get_discord_webhook_url() läser.
CREATE OR REPLACE FUNCTION public.check_stuck_pipeline_items()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  webhook_url text;
  stuck_count integer;
  summary text;
BEGIN
  -- 'processing' räknas med om den suttit fast betydligt längre än den
  -- normala 15-minuters självläkningscykeln (claim_pipeline_queue_batch) —
  -- annars kan en rad studsa pending↔processing i evighet utan att någonsin
  -- synas här, eftersom den bara sällan råkar samplas i 'pending'-läget.
  SELECT count(*) INTO stuck_count
  FROM public.report_pipeline_queue
  WHERE (status IN ('pending', 'failed') AND created_at < now() - interval '24 hours')
     OR (status = 'processing' AND claimed_at < now() - interval '2 hours');

  IF stuck_count = 0 THEN
    RETURN;
  END IF;

  SELECT public.get_discord_webhook_url() INTO webhook_url;
  IF webhook_url IS NULL THEN
    RETURN;
  END IF;

  SELECT string_agg(
    format('%s — %s (%s): %s', c.name, q.stage, q.status, coalesce(q.error, 'väntar fortfarande')),
    E'\n'
  ) INTO summary
  FROM (
    SELECT * FROM public.report_pipeline_queue
    WHERE (status IN ('pending', 'failed') AND created_at < now() - interval '24 hours')
       OR (status = 'processing' AND claimed_at < now() - interval '2 hours')
    ORDER BY created_at
    LIMIT 15
  ) q
  JOIN public.companies c ON c.id = q.company_id;

  PERFORM net.http_post(
    url := webhook_url,
    body := jsonb_build_object(
      'embeds', jsonb_build_array(jsonb_build_object(
        'title', format('%s kunder fastnade i månadsrapport-kön', stuck_count),
        'description', coalesce(summary, '') || E'\n\nÅtgärda i CRM: Kundradar → Misslyckade körningar.',
        'color', 15158332
      ))
    ),
    headers := jsonb_build_object('Content-Type', 'application/json'),
    timeout_milliseconds := 10000
  );
END;
$$;

-- ============================================================================
-- Cron-schema: seed en gång i månaden + tick var 5:e minut + daglig hälsokoll
-- ============================================================================
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- Byt ut de gamla "gör allt i en körning"-jobben mot kö-mönstret.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'monthly-website-snapshots') THEN
    PERFORM cron.unschedule('monthly-website-snapshots');
  END IF;
  IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'monthly-reports') THEN
    PERFORM cron.unschedule('monthly-reports');
  END IF;
END $$;

-- 5:e i månaden (inte 1:a) — Google Search Console har upp till 3 dygns
-- eftersläpning, så vi ger en extra dags marginal utöver värsta scenariot
-- innan vi läser data för den fullständiga föregående månaden.
SELECT cron.schedule(
  'pipeline-seed-monthly',
  '0 6 5 * *',
  $$SELECT public.seed_monthly_pipeline_queue();$$
);

SELECT cron.schedule(
  'pipeline-tick-snapshot',
  '*/5 * * * *',
  $$SELECT public.run_pipeline_tick('snapshot');$$
);

SELECT cron.schedule(
  'pipeline-tick-report',
  '*/5 * * * *',
  $$SELECT public.run_pipeline_tick('report');$$
);

SELECT cron.schedule(
  'pipeline-stuck-alert',
  '0 9 * * *',
  $$SELECT public.check_stuck_pipeline_items();$$
);
