create table if not exists "public"."calendar_events" (
  "id" bigint generated by default as identity primary key,
  "title" text not null,
  "description" text,
  "starts_at" timestamp with time zone not null,
  "ends_at" timestamp with time zone not null,
  "time_zone" text not null default 'Europe/Stockholm',
  "contact_id" bigint references "public"."contacts"(id) on delete set null,
  "company_id" bigint references "public"."companies"(id) on delete set null,
  "sales_id" bigint references "public"."sales"(id) on delete set null,
  "status" text not null default 'scheduled' check ("status" in ('scheduled', 'completed', 'cancelled')),
  "source" text not null default 'crm' check ("source" in ('crm', 'calcom', 'google')),
  "google_event_id" text unique,
  "calcom_event_id" text unique,
  "meeting_provider" text not null default 'google_meet' check ("meeting_provider" in ('google_meet')),
  "meet_link" text,
  "attendees" jsonb not null default '[]'::jsonb,
  "metadata" jsonb not null default '{}'::jsonb,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now()
);

alter table "public"."calendar_events" enable row level security;

grant select, insert, update, delete on table "public"."calendar_events" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."calendar_events" to "service_role";
grant usage, select on sequence "public"."calendar_events_id_seq" to "authenticated";
grant usage, select on sequence "public"."calendar_events_id_seq" to "service_role";

drop policy if exists "Users can view calendar_events" on "public"."calendar_events";
create policy "Users can view calendar_events" on "public"."calendar_events"
  for select
  using (auth.role() = 'authenticated');

drop policy if exists "Users can insert calendar_events" on "public"."calendar_events";
create policy "Users can insert calendar_events" on "public"."calendar_events"
  for insert
  with check (auth.role() = 'authenticated');

drop policy if exists "Users can update calendar_events" on "public"."calendar_events";
create policy "Users can update calendar_events" on "public"."calendar_events"
  for update
  using (auth.role() = 'authenticated');

drop policy if exists "Users can delete calendar_events" on "public"."calendar_events";
create policy "Users can delete calendar_events" on "public"."calendar_events"
  for delete
  using (auth.role() = 'authenticated');

create index if not exists "idx_calendar_events_starts_at" on "public"."calendar_events" ("starts_at");
create index if not exists "idx_calendar_events_sales_id" on "public"."calendar_events" ("sales_id");
create index if not exists "idx_calendar_events_contact_id" on "public"."calendar_events" ("contact_id");
create index if not exists "idx_calendar_events_status" on "public"."calendar_events" ("status");
create index if not exists "idx_calendar_events_google_event_id" on "public"."calendar_events" ("google_event_id");

drop trigger if exists "set_calendar_events_sales_id_trigger" on "public"."calendar_events";
create trigger "set_calendar_events_sales_id_trigger"
before insert on "public"."calendar_events"
for each row
execute function "public"."set_sales_id_default"();
