-- Manual sales entry tracking
-- Allows users to log actual sales figures per day/week/month,
-- independent of deal-based revenue calculations.

create table if not exists "public"."sales_entries" (
  "id" bigint generated by default as identity primary key,
  "amount" bigint not null,
  "period_type" text not null default 'month'
    check ("period_type" in ('day', 'week', 'month')),
  "period_date" date not null,
  "description" text,
  "sales_id" bigint references "public"."sales"(id) on delete set null,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now()
);

alter table "public"."sales_entries" enable row level security;

grant select, insert, update, delete on table "public"."sales_entries" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."sales_entries" to "service_role";
grant usage, select on sequence "public"."sales_entries_id_seq" to "authenticated";
grant usage, select on sequence "public"."sales_entries_id_seq" to "service_role";

drop policy if exists "Users can view sales_entries" on "public"."sales_entries";
create policy "Users can view sales_entries" on "public"."sales_entries"
  for select
  using (auth.role() = 'authenticated');

drop policy if exists "Users can insert sales_entries" on "public"."sales_entries";
create policy "Users can insert sales_entries" on "public"."sales_entries"
  for insert
  with check (auth.role() = 'authenticated');

drop policy if exists "Users can update sales_entries" on "public"."sales_entries";
create policy "Users can update sales_entries" on "public"."sales_entries"
  for update
  using (auth.role() = 'authenticated');

drop policy if exists "Users can delete sales_entries" on "public"."sales_entries";
create policy "Users can delete sales_entries" on "public"."sales_entries"
  for delete
  using (auth.role() = 'authenticated');

create index if not exists "idx_sales_entries_period_date" on "public"."sales_entries" ("period_date");
create index if not exists "idx_sales_entries_period_type" on "public"."sales_entries" ("period_type");
create index if not exists "idx_sales_entries_sales_id" on "public"."sales_entries" ("sales_id");

drop trigger if exists "set_sales_entries_sales_id_trigger" on "public"."sales_entries";
create trigger "set_sales_entries_sales_id_trigger"
before insert on "public"."sales_entries"
for each row
execute function "public"."set_sales_id_default"();
