-- Migration: Create scanner_scans table + scanner-screenshots bucket
-- Created: 2026-07-28
-- Description: Lagring för Axona Scanner (leadgen-verktyget i repot
--              "Axona Intern/scanner"): en rad per genomförd hemsidescan av ett
--              PROSPEKT, med totalpoäng 0–100, sex axelpoäng, fynd och delbar
--              rapport-slug. Medvetet separerad från website_snapshots (kundernas
--              immutabla tidsserie) så prospekt- och kunddata aldrig blandas.
--              Scannern skriver via service role; CRM-UI:t läser (poäng +
--              rapportlänk på företagskortet). Helt additiv migration —
--              inga DROP/ALTER på befintliga objekt.

CREATE TABLE IF NOT EXISTS "public"."scanner_scans" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Nullable: scans kan köras mot ad-hoc-URL:er som (ännu) inte finns i CRM:et.
  "company_id" bigint REFERENCES companies(id) ON DELETE CASCADE,
  "url" text NOT NULL,
  "final_url" text,
  "total_score" integer NOT NULL,
  "verdict" text NOT NULL,
  "verdict_band" text NOT NULL CHECK (verdict_band IN ('risk', 'needs_work', 'leaking', 'strong')),
  -- [{ key, label, score, weight, confidence, notes }]
  "axis_scores" jsonb NOT NULL DEFAULT '[]',
  -- [{ id, axis, severity, impact, title, why, fix, effort, service }]
  "findings" jsonb NOT NULL DEFAULT '[]',
  "strengths" jsonb NOT NULL DEFAULT '[]',
  -- Rådata per källa (pagespeed/seo/quality/conversion/design/places/errors)
  "raw" jsonb,
  -- Ogissbar slug för den delbara rapportsidan (scannerns /r/[slug])
  "report_slug" text NOT NULL UNIQUE,
  -- { mobile: "path", desktop: "path" } i bucketen scanner-screenshots
  "screenshot_paths" jsonb,
  "engine_version" text NOT NULL,
  "scanned_at" timestamp with time zone DEFAULT now() NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Enable RLS
ALTER TABLE "public"."scanner_scans" ENABLE ROW LEVEL SECURITY;

-- Hela teamet läser (poäng + rapportlänk i CRM-UI:t). Skrivning sker enbart
-- via scannerns service role, som inte påverkas av RLS — därför ingen
-- insert/update-policy för authenticated.
CREATE POLICY "Authenticated can view scanner scans" ON "public"."scanner_scans"
  FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE INDEX IF NOT EXISTS idx_scanner_scans_company_scanned
  ON scanner_scans(company_id, scanned_at DESC);

-- Publik bucket för bevis-skärmdumpar (mobil + desktop av publika sajter —
-- inget känsligt). Publik läsning gör att rapportsidan kan visa bilderna
-- utan signerade URL:er.
INSERT INTO storage.buckets (id, name, public)
VALUES ('scanner-screenshots', 'scanner-screenshots', true)
ON CONFLICT (id) DO NOTHING;
