-- Migration: Create call_logs table for ringlista
-- Created: 2026-03-16
-- Description: Stores call history for lead management and ringlista functionality

CREATE TABLE IF NOT EXISTS "public"."call_logs" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" bigint NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  "contact_id" bigint REFERENCES contacts(id) ON DELETE SET NULL,
  "user_id" uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  "call_outcome" text NOT NULL CHECK (call_outcome IN (
    'no_answer',
    'busy',
    'wrong_number',
    'spoke_gatekeeper',
    'spoke_decision_maker',
    'interested',
    'not_interested',
    'meeting_booked',
    'send_info',
    'callback_requested'
  )),
  "notes" text,
  "call_duration_seconds" integer,
  "followup_date" date,
  "followup_note" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Enable RLS
ALTER TABLE "public"."call_logs" ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view call_logs" ON "public"."call_logs"
  FOR SELECT
  USING (true);

CREATE POLICY "Users can insert their own call_logs" ON "public"."call_logs"
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own call_logs" ON "public"."call_logs"
  FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own call_logs" ON "public"."call_logs"
  FOR DELETE
  USING (auth.uid() = user_id);

-- Indexes for better performance
CREATE INDEX idx_call_logs_company_id ON call_logs(company_id);
CREATE INDEX idx_call_logs_contact_id ON call_logs(contact_id);
CREATE INDEX idx_call_logs_user_id ON call_logs(user_id);
CREATE INDEX idx_call_logs_created_at ON call_logs(created_at DESC);
CREATE INDEX idx_call_logs_followup_date ON call_logs(followup_date) WHERE followup_date IS NOT NULL;
